# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import serial
import serial.tools.list_ports

def getPort():
    ports = serial.tools.list_ports.comports()
    return ports

def findPort(portsFound):
    comPort = 'None'
    nbr_of_Connection = len(portsFound)
    global found_Ports

    for i in range (0,nbr_of_Connection):
        port = found_Ports[i]
        strPort = str(port)
        if 'STM' in strPort:
            splitPort = strPort.split(' ')
            comPort = (splitPort[0])
    return comPort

    def test(self):
        self.textBrowser.append("Na menjen")

found_Ports = getPort()
connectPort = findPort(found_Ports)

class Ui_controlpanel(object):
    def setupUi(self, controlpanel):
        controlpanel.setObjectName("controlpanel")
        controlpanel.resize(630, 480)
        self.centralwidget = QtWidgets.QWidget(controlpanel)
        self.centralwidget.setObjectName("centralwidget")
        self.button_base = QtWidgets.QPushButton(self.centralwidget)
        self.button_base.setGeometry(QtCore.QRect(420, 130, 171, 91))
        self.button_base.setObjectName("button_base")
        self.button_test = QtWidgets.QPushButton(self.centralwidget)
        self.button_test.setGeometry(QtCore.QRect(420, 280, 171, 91))
        self.button_test.setObjectName("button_test")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 110, 171, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.sendData())
        self.pushButton_4.setGeometry(QtCore.QRect(200, 110, 171, 91))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 200, 171, 91))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 200, 171, 91))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 320, 171, 91))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(200, 320, 171, 91))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        controlpanel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(controlpanel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 26))
        self.menubar.setObjectName("menubar")
        controlpanel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(controlpanel)
        self.statusbar.setObjectName("statusbar")
        controlpanel.setStatusBar(self.statusbar)

        self.retranslateUi(controlpanel)
        QtCore.QMetaObject.connectSlotsByName(controlpanel)

    def retranslateUi(self, controlpanel):
        _translate = QtCore.QCoreApplication.translate
        controlpanel.setWindowTitle(_translate("controlpanel", "Control Panel"))
        self.button_base.setText(_translate("controlpanel", "Base State"))
        self.button_test.setText(_translate("controlpanel", "Run Test"))
        self.pushButton.setText(_translate("controlpanel", "LEFT with 45° - ARM"))
        self.pushButton_4.setText(_translate("controlpanel", "RIGHTT with 45° - ARM"))
        self.pushButton_5.setText(_translate("controlpanel", "UP with 45° - ARM"))
        self.pushButton_6.setText(_translate("controlpanel", "DOWN with 45° - ARM"))
        self.pushButton_7.setText(_translate("controlpanel", "Head - OPEN"))
        self.pushButton_8.setText(_translate("controlpanel", "Head - CLOSE "))
        self.label.setText(_translate("controlpanel", "Control Panel"))
    
    def sendData(self):
        i = "menjen"
        var_serial = serial.Serial(connectPort, baudrate=9600, timeout=1000)
        var_serial.write(i.encode())
        #var_serial.decode("Menjen")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    controlpanel = QtWidgets.QMainWindow()
    ui = Ui_controlpanel()
    ui.setupUi(controlpanel)
    controlpanel.show()
    sys.exit(app.exec_())
