# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_05.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
import serial.tools.list_ports

def getPort():
    ports = serial.tools.list_ports.comports()
    return ports

def findPort(portsFound):
    comPort = 'None'
    nbr_of_Connection = len(portsFound)
    global found_Ports

    for i in range (0,nbr_of_Connection):
        port = found_Ports[i]
        strPort = str(port)
        if 'STM' in strPort:
            splitPort = strPort.split(' ')
            comPort = (splitPort[0])
    return comPort

    def test(self):
        self.textBrowser.append("Na menjen")

found_Ports = getPort()
connectPort = findPort(found_Ports)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 461, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.connecting_label = QtWidgets.QLabel(self.centralwidget)
        self.connecting_label.setGeometry(QtCore.QRect(480, 10, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.connecting_label.setFont(font)
        self.connecting_label.setObjectName("connecting_label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(650, 230, 131, 51))
        self.checkBox.setObjectName("checkBox")
        self.pushButton.setGeometry(QtCore.QRect(470, 60, 161, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 60, 161, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 150, 321, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 210, 161, 81))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 340, 161, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connecting_label.setText(_translate("MainWindow", "No connection"))
        self.checkBox.setText(_translate("MainWindow", "LED blink"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.pushButton_2.setText(_translate("MainWindow", "Disconnect"))
        self.pushButton_3.setText(_translate("MainWindow", "READ the errorcode"))
        self.pushButton_4.setText(_translate("MainWindow", "ControlPanel"))
        self.pushButton_5.setText(_translate("MainWindow", "Clear terminal"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

    def sendData(self):
        i = "menjen"
        var_serial = serial.Serial(connectPort, baudrate=9600, timeout=1000)
        var_serial.write(i.decode())
        #var_serial.decode("Menjen")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
